dell-dock: Add atomic support to 1_5_X
fwupd/fwupd pull request #3916
Opened 2021-10-29 09:15 UTC by bennyLucky

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [* ] Feature
- [ ] Documentation

2021-11-02 15:08 UTC, superm1 requested changes
After #3930 is merged, please cherry-pick from that and rebase on origin/1_5_X again (there is a CI fix)

2021-11-03 13:16 UTC, superm1 approved these changes
It's fine by me, but let @CragW sign off on it.

2021-11-03 13:58 UTC, bennyLucky commented
> It's fine by me, but let @CragW sign off on it.

Thanks.

2021-11-03 15:59 UTC, CragW approved these changes

2021-11-03 16:00 UTC, merged