Draft: modem-manager: detect presence of modem-power driver
fwupd/fwupd pull request #4343
Opened 2022-02-28 17:13 UTC by DylanVanAssche

Quectel EG25-G modem in the Pine64 PinePhone and PinePhone Pro
can be booted with the eg25-manager (user space) or modem-power (kernel space).
We only support the eg25-manager for upgrading these modems.

CC: @superm1 

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

2022-02-28 17:14 UTC, superm1 submitted a review, later dismissed
Looks great, thanks.

2022-02-28 17:15 UTC, DylanVanAssche commented
I don't have a kernel available with the `modem-power` driver so testing is a bit hard.
If the driver is present in the kernel, it provides a sysfs entry in `/sys/class/modem-power` like:

- `/sys/class/modem-power/modem-power/is_busy`
- `/sys/class/modem-power/modem-power/powered`
- `/sys/class/modem-power/modem-power/killswitched`
- ...

2022-02-28 17:23 UTC, superm1 commented
> I don't have a kernel available with the `modem-power` driver so testing is a bit hard. If the driver is present in the kernel, it provides a sysfs entry in `/sys/class/modem-power` like:
> 
> * ` /sys/class/modem-power/modem-power/device/is_busy`
> * `/sys/class/modem-power/modem-power/device/powered`
> * `/sys/class/modem-power/modem-power/device/killswitched`
> * ...
> 
> Source: https://github.com/megous/linux/blob/modem-5.17/drivers/misc/modem-power.c

yeah I think that's sufficient.

Fixup the CI failures and then we can merge this.

2022-02-28 17:24 UTC, superm1 commented on plugins/modem-manager/fu-mm-device.c
> +	if (g_file_test (MODEM_POWER_SYSFS_PATH, G_FILE_TEST_EXISTS) {
missing parenthesis

2022-02-28 17:57 UTC, DylanVanAssche commented
My clang-formatter was acting up, fixed :)

2022-02-28 17:59 UTC, superm1 approved these changes
OK, as long as CI passes now LGTM.

2022-02-28 19:16 UTC, hughsie requested changes
I think these need to be device inhibits. E.g added in plugin.c when the device is added. I can do an example when back home. Just before the update is deployed is too late and will scare the user.

2022-02-28 19:36 UTC, superm1 commented
> I think these need to be device inhibits. E.g added in plugin.c when the device is added. I can do an example when back home. Just before the update is deployed is too late and will scare the user.

The thing about making it an inhibit is that a kernel module can (potentially) be loaded after the daemon starts or before it quits.  So unless you do an `inotify` on `/sys/class` how will you catch that?

2022-03-02 12:39 UTC, hughsie commented
> So unless you do an inotify on /sys/class how will you catch that?

I think that's exactly what we should do. Alternate proposal in https://github.com/fwupd/fwupd/pull/4353

2022-03-02 13:36 UTC, closed without merging